import Layout from "@/components/layout";
import "@/styles/global.css";
import { Inter } from "next/font/google";

export const metadata = {
  title: "Next.js Basic CSS Example",
  description: "Generated by Next.js",
};

const inter = Inter({ subsets: ["latin"], variable: "--font-inter" });

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
